### ISSUE TITLE
python/dune/xt/grid/types.py gives me an error

### ISSUE THREAD

**Issue by ftalbrecht** [dune-community/dune-xt-grid#65]
During `cmake`:
```
CMake Error at /home/falbr_01/dune-gdt/dune-xt-common/cmake/modules/DuneXTInstallPythonPackage.cmake:21 (message):
  

  Run
  command:/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-grid/dune-env;dxt_code_generation.py;/home/falbr_01/dune-gdt/dune-xt-grid/dune/xt/grid/test/eoc_gridprovider.py;/home/falbr_01/dune-gdt/dune-xt-grid/dune/xt/grid/test/eoc_gridprovider.tpl;/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-grid/dune/xt/grid/test;/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-grid/dune/xt/grid/test/eoc_gridprovider.tpl.cc;/home/falbr_01/dune-gdt/envs/arch-minimal/local/../build-gcc-debug/dune-xt-common


  Return code: 1

  Detailed log:

  Traceback (most recent call last):

    File "/home/falbr_01/dune-gdt/envs/arch-minimal/build-gcc-debug/dune-python/python-env/bin/dxt_code_generation.py", line 6, in <module>
      exec(compile(open(__file__).read(), __file__, 'exec'))
    File "/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-common/python/scripts/dxt_code_generation.py", line 34, in <module>
      config = run_path(config_fn,init_globals=locals(), run_name='__dxt_codegen__')
    File "/usr/lib/python3.6/runpy.py", line 263, in run_path
      pkg_name=pkg_name, script_name=fname)
    File "/usr/lib/python3.6/runpy.py", line 96, in _run_module_code
      mod_name, mod_spec, pkg_name, script_name)
    File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/home/falbr_01/dune-gdt/dune-xt-grid/dune/xt/grid/test/eoc_gridprovider.py", line 5, in <module>
      all_grids = ((safe_name(g), g) for g in grid_types.all_types(cache, list(range(1, 4))) if 'Alberta' not in g)
    File "/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-grid/python/dune/xt/grid/types.py", line 33, in all_types
      for grid in  gridnames if _is_usable(grid, cache) \
    File "/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-grid/python/dune/xt/grid/types.py", line 33, in <listcomp>
      for grid in  gridnames if _is_usable(grid, cache) \
    File "/home/falbr_01/dune-gdt/environments/arch-minimal/build-gcc-debug/dune-xt-grid/python/dune/xt/grid/types.py", line 18, in _is_usable
      return cache[guards[grid]]

  KeyError: 'ALBERTA_FOUND'

Call Stack (most recent call first):
  /home/falbr_01/dune-gdt/dune-xt-common/cmake/modules/DuneXTTesting.cmake:111 (dune_xt_execute_process)
  dune/xt/grid/test/CMakeLists.txt:23 (begin_testcases)
```
I do not have alberta installed and looking at the cache did not ive me any immediate insights. Any thoughts?

**Comment by renemilk** [comment]
Is this a cmake re-run or first run from dunecontrol? Which commit's xt-grid at?

**Comment by renemilk** [comment]
Also, I assume this is cmake 3.11.x?

**Comment by renemilk** [comment]
We just saw this in debian-minimal too. @TiKeil will PR a quickfix of mine soonish.

**Comment by ftalbrecht** [comment]
K, sorry for lagging behind. I've had this in debian-minimal, `cmake == 3.7.2`.

**Comment by renemilk** [comment]
Assumed fixed
